CONF_FINGERPRINT = "fingerprint"
CONF_USERNAME = "username"
CONF_PASSWORD = "password"
CONF_HOSTNAME = 'hostname'
CONF_POLLING = 'polling'
ADTPULSE_DOMAIN = 'adtpulse'
DEFAULT_SCAN_INTERVAL='1'
ADTPULSE_URL_US = 'https://portal.adtpulse.com'
ADTPULSE_URL_CA = 'https://portal-ca.adtpulse.com'